Repository kovdan01/melon, pull requests merged in 2021-03, with the labels that each got.

#91 Add Model-View-Controller concept
  src/client-desktop/CMakeLists.txt
  src/client-desktop/include/chat_list_model.hpp
  src/client-desktop/include/chat_list_view.hpp
  src/client-desktop/include/chat_list_widget.hpp
  src/client-desktop/include/chat_widget.hpp
  src/client-desktop/include/main_window.hpp
  src/client-desktop/include/message_list_model.hpp
  src/client-desktop/include/ram_storage.hpp
  src/client-desktop/src/chat_list_model.cpp
  src/client-desktop/src/chat_list_view.cpp
  src/client-desktop/src/chat_widget.cpp
  src/client-desktop/src/main.cpp
  src/client-desktop/src/main_window.cpp
  src/client-desktop/src/message_list_model.cpp
  src/client-desktop/ui/chat_widget.ui
  src/client-desktop/ui/main_window.ui
Labels: enhancement

#106 Enhance messages & chats display
  src/client-desktop/CMakeLists.txt
  src/client-desktop/include/chat_item_delegate.hpp
  src/client-desktop/include/chat_list_model.hpp
  src/client-desktop/include/chat_widget.hpp
  src/client-desktop/include/config.hpp
  src/client-desktop/include/main_window.hpp
  src/client-desktop/include/message_item_delegate.hpp
  src/client-desktop/include/message_list_model.hpp
  src/client-desktop/include/ram_storage.hpp
  src/client-desktop/src/chat_item_delegate.cpp
  src/client-desktop/src/chat_list_model.cpp
  src/client-desktop/src/chat_widget.cpp
  src/client-desktop/src/main_window.cpp
  src/client-desktop/src/message_item_delegate.cpp
  src/client-desktop/src/message_list_model.cpp
  src/client-desktop/ui/chat_widget.ui
  src/core/include/melon/core/storage_class.hpp
  src/core/include/melon/core/storage_class.ipp
Labels: enhancement

#120 Fix various issues (see description for details)
  .github/workflows/linux-macos.yml
  src/client-desktop/CMakeLists.txt
  src/client-desktop/include/helpers.hpp
  src/client-desktop/include/message_list_model.hpp
  src/client-desktop/src/chat_item_delegate.cpp
  src/client-desktop/src/chat_list_model.cpp
  src/client-desktop/src/main_window.cpp
  src/client-desktop/src/message_item_delegate.cpp
  src/client-desktop/src/message_list_model.cpp
  src/core/CMakeLists.txt
  src/core/include/melon/core/entities.hpp
  src/core/include/melon/core/entities.ipp
  src/core/include/melon/core/exception.hpp
  src/core/src/entities.cpp
  src/server/storage/include/storage.hpp
  src/server/storage/sql/db_scheme_dump.sql
  src/server/storage/src/main.cpp
  src/server/storage/src/storage.cpp
Labels: bug, enhancement

#121 Fix DB scheme
  src/core/include/melon/core/entities.hpp
  src/core/include/melon/core/entities.ipp
  src/core/src/entities.cpp
  src/server/storage/include/storage.hpp
  src/server/storage/sql/db_scheme_dump.sql
  src/server/storage/src/main.cpp
  src/server/storage/src/storage.cpp
Labels: bug
